export const SET_MESSAHE ='SET_MESSAHE'
export const CLEAR_MESSAGE='CLEAR_MESSAGE'
export const CLEAR_SUCCESS='CLEAR_SUCCESS'
export const ERROR = 'ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const EDIT_FORM = 'EDIT_FORM'
export const CLEAR_EDITFORM = 'CLEAR_EDITFORM'

export const SUCCES_REGISTER='SUCCES_REGISTER'
export const SUCCES_LOGIN='SUCCES_LOGIN'
export const LOG_OUT='LOG_OUT'
export const SET_ADMIN='SET_ADMIN'
export const SET_USER='SET_USER'
export const SET_ALL='SET_ALL'
export const DELETE_AUTH='DELETE_AUTH'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const SEND_FORGET_REQUEST = 'SEND_FORGET_REQUEST'
export const RESET_REQUEST = 'RESET_REQUEST'


export const ADD_PROFILE = 'ADD_PROFILE'
export const GET_PROFILE = 'GET_PROFILE'
export const EDIT_PROFILE = 'EDIT_PROFILE'
export const DELETE_PROFILE = 'DELETE_PROFILE'


export const GET_PRODUCT= 'GET_PRODUCT'
export const UPLOAD_PRODUCT= 'UPLOAD_PRODUCT'
export const UPDATE_PRODUCT= 'UPDATE_PRODUCT'
export const DELETE_PRODUCT= 'DELETE_PRODUCT'
export const ADD_CART = 'ADD_CART'


export const GET_CUSTOMERS= 'GET_CUSTOMERS'
export const GET_CUSTOMER= 'GET_CUSTOMER'
export const ADD_CUSTOMER= 'ADD_CUSTOMER'
export const UPDATE_CUSTOMER= 'UPDATE_CUSTOMER'
export const DELETE_CUSTOMER= 'DELETE_CUSTOMER'
export const SEARCH_CUSTOMER = 'SEARCH_CUSTOMER'

export const GET_INVOICES= 'GET_INVOICE'
export const GET_SINGLE_INVOICE= 'GET_SINGLE_INVOICE'
export const ADD_INVOICE= 'ADD_INVOICE'
export const UPDATE_INVOICE= 'UPDATE_INVOICE'
export const DELETE_INVOICE= 'DELETE_INVOICE'





   
   




